spring.application.name=billing-service

# ===============================
# SERVER
# ===============================
server.port=8084

# ===============================
# DATABASE
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/billing_db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA
# ===============================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# ===============================
# FLYWAY
# ===============================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# ===============================
# GRAPHQL
# ===============================
spring.graphql.graphiql.enabled=true



# ===============================
# ACTUATOR
# ===============================
management.endpoints.web.exposure.include=health,info,prometheus

management.endpoint.health.show-details=always